cucumber-rails.gemspec

...so that projects that for example don't need ActiveRecord don't automatically have to include it (rails depends on activerecord etc., railties does not).

Depend on railties instead of rails

---

features/annotations.feature
features/support/version_hooks.rb
lib/generators/cucumber/install/templates/tasks/cucumber.rake.erb

For Rails 4.0+, the generator will add configuration entries to
config/environments/development.rb to include Cucumber's features
directory and .feature files in the "rake notes" run.

Add annotations configuration in generator

---

cucumber-rails.gemspec

The tests pass locally. Built on top of #303 because the tests are failing
for reasons other than mime-types changes.

Expand support to include mime-types 3

---

History.md

This PR formats the History.md changelog document to avoid ill-formed links to PRs.
- and I spelled my name like I spell it

History.md: markdown formatting fix

---

CHANGELOG.md

CHANGELOG.md updates as per [cucumber/cucumber #251](https://github.com/cucumber/cucumber/issues/251)
* Renamed History.md to CHANGELOG.md
* Added contributing note to beginning of file
* Added line for my changes
* Split current unreleased changes into groups

CHANGELOG update for monorepo #251

---

lib/cucumber/rails/hooks/database_cleaner.rb

There are strange issues on CI environment with Ruby 2.0.0 and 2.1.0, so I'm reverting this particular change. This undoes part of https://github.com/cucumber/cucumber-rails/pull/348

Restored DatabaseCleaner hook.

---

CHANGELOG.md
lib/cucumber/rails/hooks/database_cleaner.rb

This was dependent on us removing support for Ruby <= 2.1. Now that that is done (#360), we can add this back and the tests _should_ pass. :+1:

Reinstate new form of tag negation.

---

README.md

Removed the PullReview badge from the Readme, as PullReview has shut down.
http://blog.8thcolor.com/en/2018/02/the-end/?utm_source=blog.8thcolor.com&utm_medium=banner&utm_campaign=blog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cucumber/cucumber-rails/366)

Remove PullReview badge from README

---

cucumber-rails.gemspec
spec/spec_helper.rb

The latest version of ammeter loads capybara/rails, which in turn means Rails.application needs to be present. Somewhere, a connection pool is needed too.

Update for ammeter 1.1.4

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template incorrectly advises contributors to prefix the PR with the name of the sub-project, however cucumber-rails is not part of the cucumber mono-project, as identified in @mvz's review, [here](https://github.com/cucumber/cucumber-rails/pull/367#pullrequestreview-110264630).
```
NAMING YOUR PULL REQUEST: Please prefix your PR with the name of the sub-project
e.g. `tag-expressions: Refactor checks`
```
I've changed this to:
```
NAMING YOUR PULL REQUEST: Please choose a concise, descriptive name for your pull request.
```
I've added some guidance for how to name a PR.
To make the process of submitting a PR less confusing for contributors.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Improve accuracy of Github PR template

---

config/cucumber.yml
features/rerun_profile.feature
lib/generators/cucumber/install/templates/config/cucumber.yml.erb
lib/generators/cucumber/install/templates/support/_rails_each_run.rb.erb

The old tag negation syntax was left in a few places. This replaces them with the new syntax.
This is WIP because it depends on #372 which touches some of the same lines.
Fixes remaining causes of #346.
Existing tests should still pass.

Use new tag negation syntax everywhere

---

config/cucumber.yml
features/rerun_profile.feature
lib/generators/cucumber/install/templates/config/cucumber.yml.erb

The rerun format generated by cucumber-ruby has changed (see https://github.com/cucumber/cucumber-ruby/issues/1162). This PR updates the cucumber.yml files, both of the project and the generated one, to handle this.
Instead of spaces, the rerun format now uses newlines. Handle this by replacing all whitespace with spaces.
After failing multiple scenarios, running cucumber again would fail, complaining that cucumber.yml couldn't be read.
I have tested the generated file by updating the relevant feature file with a multi-line rerun file. I have tested the changes to the project file by force-failing two scenarios and checking that could run `bundle exec cucumber` without problems.

Handle rerun files with multiple lines

---

features/allow_rescue.feature
lib/cucumber/rails/action_controller.rb

<em>This is the same as [#296 (PR)](https://github.com/cucumber/cucumber-rails/pull/296), but has been rebased onto the latest changes to master. The following summary is copied from the other PR.</em>
`@allow-rescue` permits rescuing exceptions by setting `action_dispatch.show_exceptions` to true in the env hash. However, this will render the detailed error page and not the public error page you'd encounter in production.
Given that the feature enables testing of error pages, and seems to be intended to mirror production behaviour as per the comment on https://github.com/cucumber/cucumber-rails/blob/master/lib/generators/cucumber/install/templates/support/_rails_each_run.rb.erb#L6-L14, this PR sets `action_dispatch.show_detailed_exceptions` to false, thus enabling the public error page …

[Rebased] Disable display of detailed exceptions

---

lib/generators/cucumber/install/install_generator.rb

The interface of `ERB.new` will change from Ruby 2.6.
> Add :trim_mode and :eoutvar keyword arguments to ERB.new.
> Now non-keyword arguments other than first one are softly deprecated
> and will be removed when Ruby 2.5 becomes EOL. [Feature #14256]
https://github.com/ruby/ruby/blob/2311087/NEWS#stdlib-updates-outstanding-ones-only
Related PR: https://github.com/cucumber/cucumber-ruby/pull/1301

Deprecate safe_level of ERB.new in Ruby 2.6

---

.travis.yml

Exclude Rails 4.2 + ruby-head (2.6) build matrix from Travis CI.
This PR excludes the following error matrix from Travis CI.
```console
NoMethodError:
undefined method `new' for BigDecimal:Class
```
https://travis-ci.org/cucumber/cucumber-rails/jobs/462430088#L1569-L1594
Rails 4.2 is using `BigDecimal.new`. However `BigDecimal.new` was removed from Ruby 2.6.
https://github.com/ruby/ruby/commit/2810c12a99fed7297d558d8b1aaaf755eb8b8a2d#diff-64cf76d72ee12a82d3093efe6c2f83f7
```console
% ruby -rbigdecimal -ve 'BigDecimal.new(5.0)'
ruby 2.6.0dev (2018-12-10 trunk 66302) [x86_64-darwin17]
/Users/koic/.rbenv/versions/2.6.0-dev/lib/ruby/site_ruby/2.6.0/rubygems/version.rb:216:
warning: deprecated Object#=~ is called on Integer; it always returns
nil
Traceback (most recent call last):
-e:1:in …
```

Exclude Rails 4.2 + ruby-head (2.6) build

---

lib/generators/cucumber/install/install_generator.rb

There was a mistake in the keyword argument of `ERB.new` for Ruby 2.6.0-dev.
This PR fixes the following errors for Ruby 2.6.0-dev CI matrix.
```console
1) Cucumber::InstallGenerator no arguments config/cucumber.yml
Failure/Error: ERB.new(IO.read(template), trim_mode: nil, eoutvar:  '-').result(binding).gsub(/^/, indent)
SyntaxError:
(erb):1: syntax error, unexpected '='
- = +''; -.<< "require 'cucumber...
^
(erb):1: syntax error, unexpected '.'
- = +''; -.<< "require 'cucumber/rails'\...
^
(erb):2: syntax error, unexpected end-of-input
(snip)
Finished in 0.04433 seconds (files took 1.34 seconds to load)
16 examples, 11 failures
```
https://travis-ci.org/cucumber/cucumber-rails/jobs/465896307
The above error is a regression by #399 💦 This PR handles `trim_mode` correctly.

Fix an error for ruby-head (2.6) CI matrix

---

.travis.yml

Fix a build error for Ruby 2.2 matrix on Travis CI.
This PR fixes the following build error.
```console
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.1.gem (100%)
ERROR:  Error installing rubygems-update:
rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```
https://travis-ci.org/cucumber/cucumber-rails/jobs/471780986#L480-L487
RubyGems 3.0.1 requires Ruby 2.3.0 or higher.
https://github.com/rubygems/rubygems/blob/v3.0.1/rubygems-update.gemspec#L32

Fix a build error for Ruby 2.2 matrix on Travis CI

---

.travis.yml

This reverts commit e4b7e5fd11f042c5fc532b9798a0ae5faf130e61.
This PR restores Rails 4.2 + ruby-head (2.6) build.
`BigDecimal.new` has been replaced with deprecation rather than deletion.
```console
% ruby -rbigdecimal -ve 'BigDecimal.new(42)'
ruby 2.6.0dev (2018-12-24 trunk 66524) [x86_64-darwin17]
-e:1: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```
Follow up of https://github.com/cucumber/cucumber-rails/pull/400#issuecomment-447177153.

Revert "Exclude Rails 4.2 + ruby-head (2.6) build"

---

Appraisals
features/step_definitions/cucumber_rails_steps.rb
gemfiles/rails_4_2.gemfile
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_2.gemfile

Force the use of sqlite3 version 1.3.x when running scenarios that test installing Rails and cucumber-rails. Since these scenarios break out of the bundle created by the gemspec, they might otherwise pick up later versions of sqlite3 by accident.
This is currently causing build failures with Rails 4.2 and 5.0, since they have no released version with support for sqlite3 1.4.
Add a gem line for sqlite3 to the relevant cucumber step.
The Travis build is currently failing.
Running the full test suite for Rails 5.2. Travis will test the other versions.
- Bug fix (non-breaking change which fixes an issue).

Ensure working version of sqlite3 is used in scenarios

---

features/step_definitions/cucumber_rails_steps.rb

Removes clunk from stdout from using deprecated aruba methods
Same as above
Remove stdout pollution so it's easier to see terminal output
N/A

Use newer aruba methods instead of deprecated ones

---

features/step_definitions/cucumber_rails_steps.rb
features/support/cucumber_rails_helper.rb
features/support/env.rb

Remove Aruba reporting monkey-patch
Removes code from Cucumber-Rails that tests for ARUBA_REPORT_DIR and overrides Aruba's reporting code. Also removes `prepare_aruba_report` calls from the step definitions.
Aruba reporting is deprecated and broken with Cucumber 2 and up, and Cucumber-Rails requires Cucumber 3. Therefore, it is safe to say that no-one is using this feature for running Cucumber-Rails' test suite.
I ran `ARUBA_REPORT_DIR=tmp bundle exec rake` without this change and it fails, even after adding `bcat` as a dependency, with the message:
```
undefined method `line' for #<Cucumber::Core::Test::Case: features/allow_rescue.feature:20> (NoMethodError)
```
Basically a cleanup. Removes something that was broken.

Remove Aruba reporting monkey-patch

---

features/support/cucumber_rails_helper.rb

Here's a quick attempt to fix the CI failure problem on ruby 2.7.0, aka #426

Avoid using bootsnap on CI for stable builds

---

CHANGELOG.md

This amends the CHANGELOG document to include the latest work on removing Ruby 2.2 support.
See #425 
- Also: Fix compare link in title of "master release".
- Also: Format usernames using reference-style links. What do you think about that? Should I complete it throughout the document? We _are_ hand-writing this, so it ought to simplify things.
I hope we soon get to release a new version.
I previewed.

Update CHANGELOG to include removal of Ruby 2.2

---

cucumber-rails.gemspec
spec/cucumber/rails/database_spec.rb

Updates the `rubocop` and `rubocop-rspec` dependencies to their latest version, and fixes new detected offenses.
* Update `rubocop` to `0.74.0`
* Update `rubocop-rspec` to `1.35.0`
* Update wording of `context` block so it includes `with`
* Restructure a spec to avoid creating new constants inside that spec
Keeps things up-to-date.
I ran rubocop and the specs again after this change.

Update RuboCop and RuboCop-RSpec, and fix new offenses

---

Rakefile

Fixes a small bug that makes mis-typing the argument for `rake test:gemfile` raise the wrong error.
Adds a comma so `ArgumentError` is not interpreted as a (non-existent) method.
Makes the error message actually useful.
I tested it with an incorrect invocation of this rake task.

Fix Rakefile error handling

---

cucumber-rails.gemspec

Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `mailing_list_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/cucumber-rails), via the Rubygems API, and the `gem` and `bundle` command-line tools with the next release.
Also update the homepage URL.

Add project metadata to the gemspec

---

cucumber-rails.gemspec
features/allow_rescue.feature
features/step_definitions/cucumber_rails_steps.rb
features/support/cucumber_rails_helper.rb
lib/cucumber/rails.rb
lib/cucumber/rails/database.rb
lib/cucumber/rails/hooks/active_record.rb
lib/cucumber/rails/hooks/mail.rb

This PR fixes a couple of small syntax issues, it adds a new core-dependency (Which simplifies a lot of logic and doesn't really change XP)
- Remove some conditional hooks, that aren't needed
- Use Better Ruby Syntax
Remove un-needed lines of code. Simplify contributor block
CI

Dependency Update / Ruby Syntax overhaul

---

lib/cucumber/rails/world.rb

The build is failing with multiple occurrences of the following error:
`uninitialized constant Cucumber::Rails::ActionDispatch::IntegrationTest
(NameError)`
Example:
https://travis-ci.org/cucumber/cucumber-rails/jobs/650040930
I have also encountered this error when pointing a project at a local build
of `cucumber-rails` at `master`.
As `IntegrationTest` does not live in the
`Cucumber::Rails::ActionDispatch` namespace, this commit makes the
change to read `ActionDispatch::IntegrationTest` from the global
namespace.

Resolve NameError occurring in TravisCI

---

CHANGELOG.md
lib/cucumber/rails.rb

Avoid printing out warning when `cache_classes` needs to be `false`.
The `cache_classes` setting needs to be `false` when Spring is used. In this
case cucumber-rails doesn't have to print out the warning.
See https://github.com/rails/spring/issues/598#issuecomment-528121218.
I'm not sure whether this change requires tests, it probably doesn't make sense
to pull in Spring just for that.

Skip cache_classes warning when using Spring

---

features/choose_javascript_database_strategy.feature
features/support/cucumber_rails_helper.rb
lib/cucumber/rails/database.rb

Trying to fix a deprecation message coming from the `database_cleaner` gem.
Fixes #459.
My changes consist of:
* For the usage inside "lib", make sure to use the proper API according to its availabilty. That means using `DatabaseCleaner.cleaners [if available](https://github.com/DatabaseCleaner/database_cleaner/commit/d226e25312bdd2f2e1705f832b3e39612e3eee8e).
* For the usages inside our own features, bump the `database_cleaner` in use to a high enough version, and switch to `DatabaseCleaner.cleaners` unconditionally.
Remove deprecation messages from test suites.
Not yet, I'll start with CI, then test it on my project.

Fix deprecation

---

.rubocop.yml
.travis.yml
cucumber-rails.gemspec
features/step_definitions/cucumber_rails_steps.rb
features/support/cucumber_rails_helper.rb

Update the set of tested and supported Rubies to 2.4 - 2.7
- Bump minimum version in gemspec and rubocop config
- Stop building on 2.3 on Travis
- Start building on 2.7 on Travis
- Update rubocop and aruba dependencies, which also support Ruby 2.4+
This relates to #455 and lowers the maintenance burden.
Travis will have to check on all supported Rubies.
Not sure.
Not sure yet either.

Support for Ruby 2.4 through 2.7

---

CHANGELOG.md
features/database_cleaner.feature
features/step_definitions/cucumber_rails_steps.rb
features/support/cucumber_rails_helper.rb
lib/cucumber/rails/hooks/database_cleaner.rb

Hi folks! This PR aims to resolve some incompatibilities with cucumber-rails and the upcoming major v2 release of database_cleaner.
In order to get access to the database_cleaner configuration in a ORM-agnostic way, we first try to require `database_cleaner/core` (which is only available in the database_cleaner v2 family of gems), then fall back to requiring `database_cleaner` for folks still on v1, finally falling back to silence if neither is available, since database_cleaner is an optional dependency.
Last week, we cut beta versions of the next major version of database_cleaner. The main change here is that all of the ORM adapters have been split off into their own gems, e.g. database_cleaner-active_record, database_cleaner-redis, etc. Understanding that the majority of …

Compatibility with database_cleaner v2 adapter gems

---

lib/cucumber/rails/database.rb

`DatabaseCleaner::VERSION` didn't exist until `1.8.0.beta`, so having an older version causes an uninitialized constant error instead of using the old behavior.
When upgrading the cucumber-rails 2.1, my @javascript scenarios failed with `uninitialized constant DatabaseCleaner::VERSION (NameError)` errors. cucumber-rails has conditional logic checking if `DatabaseCleaner::VERSION` is greater than or equal to `1.8.0.beta`, but `DatabaseCleaner::VERSION` [didn't exist until `1.8.0.beta`](https://github.com/DatabaseCleaner/database_cleaner/commit/db6b5d1d547647cbb5c07ecd5740019d2493dd2b#diff-c4f8e099c1ca7e218458213e7c82ac59).
The code change that added support for newer versions of Database Cleaner was written with the intention of maintaining support for older versions of Database Cleaner, …

Restore compatibility with database_cleaner < 1.8.0.beta

---

.rubocop.yml
cucumber-rails.gemspec

Hi,
Thanks again for working on this! :heart: 
However, while maintaining this in Debian, we found that this library relies on `git` to list the files which could be done via pure Ruby alternative -- which is what this PR does.
Also, added rubocop-packaging as a `development_dependency` which will ensure the best practices.
Here's what it shows:
```
Inspecting 33 files
...C.............................
Offenses:
cucumber-rails.gemspec:49:24: C: Packaging/GemspecGit: Avoid using git to produce lists of files.
Downstreams often need to build your package in an environment that does not have git (on purpose).
Use some pure Ruby alternative, like Dir or Dir.glob.
s.files            = `git ls-files`.split("\n")
^^^^^^^^^^^^^^
cucumber-rails.gemspec:50:24: C: Packaging/GemspecGit: Avoid using …
```

Drop `git ls-files` in gemspec

---

CHANGELOG.md
lib/cucumber/rails/hooks/active_record.rb

This commit reverts part of 9f18bb437cd8039aaa4d9f19f67544211205ace3.
While Rails has included ActiveRecord since the very beginning, not every Rails app uses ActiveRecord or even loads ActiveRecord. Some use alternative databases entirely.
The commit mentioned above asserts that conditionals on ActiveRecord are not necessary for cucumber-rails because Rails includes ActiveRecord and always has. The problem is that not every Rails app uses or loads ActiveRecord. This was in fact a cornerstone of the Rails 3 release where the components were made more easily replaceable, which led to the introduction of the `Railtie` class and the ActiveModel library.
The portion of the commit that was not reverted deals with requiring the `rails/test_help` file and doing so unconditionally. This is a …

Restore previous behavior where ActiveRecord hooks are conditional

---

.rubocop.yml
cucumber-rails.gemspec
lib/cucumber/rails.rb

Update RuboCop dependencies, enable new cops by default, and fix new offense
- Updates rubocop, rubocop-rspec, rubocop-performance and rubocop-packaging to their latest versions
- Enables new cops by default instead of having to enable each separately. Since versions of the rubocop gems are updated carefully, this turns out to be less work in general
- Fix new Performance/StringInclude offense
Keeps things up-to-date
I ran rubocop to check that it's clean now.

Update RuboCop dependencies and fix new offense

---

lib/cucumber/rails/hooks/mail.rb

ActionMailer is optional on Rails and should also be optional here.
By checking for the presence of the class, we allow apps that don't use action mailer to use the gem.
This change is harmless and makes the gem compatible with more apps.
Edited the gem on my local machine and cucumber runs after the change

Check for ActionMailer before adding mailer hook

---

Appraisals
CHANGELOG.md
cucumber-rails.gemspec
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_2.gemfile
gemfiles/rails_6_0.gemfile

By only depending on railties, optional rails gems are not pulled
in automatically, leaving apps with fewer dependencies.
By depending on rails, cucumber-rails forces apps depending on it to pull
in all Rails gems, including optional ones such as actioncable
or activejob. This leaves apps more bloated than they have to be.
Tests are still passing.

Stop including all Rails gems

---

CHANGELOG.md

I was updating some dependencies in my project and went through the changelogs for the outdated gems. Then I found that the latest release wasn't renamed to the version number in the changelog

Fix the version number for latest release in CHANGELOG.md

---

.rubocop.yml
cucumber-rails.gemspec

RuboCop::Packaging through v0.5 supports
autocorrect for its cops. Thus worth bumping
the version from v0.3 to v0.5.
And also sort the list of extensions alphabetically.
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

Bump RuboCop::Packaging to v0.5

---

CHANGELOG.md

An author was missing a reference-style link in the Markdown document.
Add a link in there.
Makes the CHANGELOG render right.
Preview the Markdown.

CHANGELOG: fix Markdown link to a user which lacked a link

---

features/support/hooks.rb

Replace puts with log to silence Cucumber warnings.
This replaces puts with log in the After scenario hook that prints output of failed commands when the scenario fails.
Cucumber's old puts behavior is deprecated. This change silences warnings from Cucumber about this.
I re-ran one scenario that fails on my machine to see if the warnings disappeared.

Silence warnings about puts versus log

---

.github/workflows/build.yml
features/support/cucumber_rails_helper.rb

Speed up the CI build by instructing Rails to skip Javascript when creating a new application.
In the Cucumber test suite for this gem, multiple temporary Rails applications are created to exercise the integration. For the Rails 6.0 test jobs in-particular, this is extremely slow. The `webpacker:install` step takes a long time to complete.
By removing this step and instructing Rails to skip installing Javascript configuration, we can speed up the build. The Rails 6.0 test job build times are improved by at least 50%! From ~20mins to <10mins.
It's frustrating to wait for a slow CI build. Developers want feedback ASAP.
CI configuration change only. The CI build passes.

Skip Javascript when creating a Rails application in test suite

---

features/no_database.feature
features/rerun_profile.feature
features/support/cucumber_rails_helper.rb

The Cucumber test suite for this gem can take some time to run. It'd be great to speed this up and provide a faster feedback loop for developers.
Each scenario of the Cucumber test suite creates a temporary Rails application with which to test the `cucumber-rails` integration. There are optimisations that can be made to reduce the time spent creating these Rails applications.
This proposal focuses on the gem installation of the Rails applications. With these four optimisations, the CI build is reduced from **~10** minutes to **~5** minutes!
- **Avoid installing unnecessary gems**: The Rails framework provides much functionality. The `cucumber-ralis` gem only integrations with a small portion of this functionality. All we need to provide confidence, is the MVC functionality provided by …

Optimise CI test suite

---

README.md

Since #506, the test suite no longer requires a Javascript runtime. Remove the instruction to install one from the README document.

Remove instruction to install a Javascript runtime

---

cucumber-rails.gemspec
lib/cucumber/rails/database/strategy.rb
spec/cucumber/rails/database_spec.rb

Raise useful error if no DatabaseCleaner strategies are loaded
When `#before_js` is called on a Strategy, bail out if DatabaseCleaner.cleaners is empty.
This fixes #491.
I added a spec and made it pass.

Raise useful error if no DatabaseCleaner strategies are loaded

---

.github/workflows/build.yml
CHANGELOG.md
cucumber-rails.gemspec

Attempt to add support for Ruby 3.
I've added a new entry in the build matrix. Ruby 3 is only properly supported with Rails 6.1.
I have updated the runtime dependencies in the gemspec. I have tried other ways without success.

Add support for Ruby 3

---

CHANGELOG.md
features/choose_javascript_database_strategy.feature
lib/cucumber/rails.rb
lib/cucumber/rails/database.rb
lib/cucumber/rails/database/null_strategy.rb
spec/cucumber/rails/database_spec.rb

Presently there is no nice way to disable `@javascript` tag handling without writing a custom database strategy class. See #521
This PR adds a null database strategy to allow easily doing so by
```
Cucumber::Rails::Database.javascript_strategy = :none
```
I'm planning to add some other enhancements and documentation later to allow custom list of tags but having a null strategy is useful anyway and is a first step.

null database strategy to disable @javascript handling

---

.github/workflows/build.yml
Appraisals

Seems that when cucumber dependency was upgraded to 6 (#515) changes to apparaisals weren't commited

Add missing Appraisals changes

---

.github/workflows/build.yml
.rubocop.yml
CHANGELOG.md
cucumber-rails.gemspec
dev_tasks/yard/default/layout/html/setup.rb
lib/generators/cucumber/install_generator.rb

- Target 2.5+ in gemspec, RuboCop config
- Fix new RuboCop offense
- Add Ruby 3.1 to github actions matrix
Rubocop requires an upgrade to 1.22.1 or higher to run on Ruby 3.1. Older versions generate the following error
```
An error occurred while Layout/BlockAlignment cop was inspecting cucumber-rails/features/support/aruba.rb:3:0. 
```
Rubocop 1.22.1 doesn't support ruby 2.4. Since ruby 2.4 EOL date is 2020-03-31 (almost two years ago) dropping support to add the latest ruby seems a good call.
The PR also downgrades ruby 2.5 version from 2.5.9 to 2.5.8. The reason is the following. Upgrading rubocop introduced a new dependency `unicode-display_width`. Bundler is unable to download it due `ArgumentError: wrong number of arguments (given 4, expected 1)`.  According to [this …

Add ruby 3.1 & drop ruby 2.4

---

.github/workflows/build.yml

Tweaks to running matrix ready for 2.5 release (This hasn't been checked in a while, and was a bit vague)

Prep for release 2 5

---

cucumber-rails.gemspec

Correct `rubygems_version` to `required_rubygems_version` in cucumbe-rails.gemspec.
`rubygems_version` was used, probably a mistake for `required_rubygems_version`.
Because `rubygems_version` should not be set.
refs: https://github.com/rubygems/rubygems/blob/cc6f96aa0c1c99d94363d12884001a2de28da033/lib/rubygems/specification.rb#L530-L534

Use `required_rubygems_version` instead of `rubygems_version`

---

CHANGELOG.md
features/capybara_javascript_drivers.feature
features/step_definitions/cucumber_rails_steps.rb
lib/cucumber/rails/capybara/select_dates_and_times.rb

Fixes #534
Rails 7 changed default scaffold datetime helper from `datetime_select` to `datetime_field`. PR #526 forces capybara helper to work only with `datetime_field`. That's fine for this gem feature specs but not for other projects.
This PR adds the ability to work with both helpers.
I'm adding another spec forcing select boxes to view helper. Both `datetime_select` and `datetime_field` have
been around since Rails 5.

Add support for alternative select boxes date field helpers

---

Appraisals
CONTRIBUTING.md
Rakefile
cucumber-rails.gemspec
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_2.gemfile
gemfiles/rails_6_0.gemfile
gemfiles/rails_6_1.gemfile
gemfiles/rails_7_0.gemfile

Build failures fix - Primarily related to a couple of gems not liking ruby2 vs ruby3 syntax
- Fix up Appraisals build contexts
- Add new guards
- Double check version decrements for old version support
Fix stuff
CI

bugfix: build failures

---

lib/cucumber/rails/world.rb

Pass all rubocop-performance rules, also in latest. #543 failed a check.
Just followed the tip.
Green is good.
CI only.

linting: fix Performance/StringIdentifierArgument

---

README.md

This changes the URL to the build status badge to a working one.
There was a broken image in the README.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

Use GitHub Actions badge in README.md [ci skip]

---

README.md

I removed two broken badges.
There is no active website on the other side of this URL.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

Drop defunct badges from README.md [ci skip]
