cucumber/cucumber-rails

.travis.yml
cucumber-rails.gemspec
features/allow_rescue.feature
features/capybara_javascript_drivers.feature
features/choose_javascript_database_strategy.feature
features/database_cleaner.feature
features/disable_automatic_database_cleaning.feature
features/emulate_javascript.feature
features/rerun_profile.feature
features/rest_api.feature
features/step_definitions/cucumber_rails_steps.rb
features/support/env.rb

Specs and features are green with these changes when using the main Gemfile. Hopefully it will make the other variations green as well.

Fix testing

---

cucumber-rails.gemspec

Allow any cucumber < 3

---

lib/generators/cucumber/install/install_generator.rb

Be a good Unix citizen and end with a newline - http://stackoverflow.com/a/729795/191127

Add new line to end of generated database.yml

---

CONTRIBUTING.md

please accept my name as a maintainer of this gem ! cheers

Mathieu Jobin as a release managers

---

CONTRIBUTING.md

This PR fixes a tiny typo in the CONTRIBUTING docs.

CONTRIBUTING.md: Fix typo

---

features/step_definitions/cucumber_rails_steps.rb

Following on from: https://github.com/cucumber/cucumber-rails/issues/356

[WIP] Fix tests for Rails 4.0 and 4.2 on Ruby 2.1.10 - CI environment

---

CHANGELOG.md
README.md

As per https://github.com/cucumber/cucumber-rails/issues/361. Also tidied up the changelog.

Updated README about Ruby versions; Tidied changelog.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Added the Issue & PR Templates to bring cucumber-rails in-line with the [cucumber](https://github.com/cucumber/cucumber) repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cucumber/cucumber-rails/367)

Added Github Issue & PR templates

---

CONTRIBUTING.md

I'd like to request release karma, so I can push to rubygems.org. My rubygems.org email address is andrew@xtrasimplicity.com. 
Thanks! 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cucumber/cucumber-rails/388)

Requesting release karma

---

README.md

This PR embellishes the README to make the Ruby sections stand out more.

README: Syntax highlight code snippets

---

CONTRIBUTING.md
README.md

Update instructions to make sure all development dependencies are installed.
Mention the `install_geckodriver.sh` and `install_webpacker.sh` in both README and CONTRIBUTING.
I completely missed `install_geckodriver.sh` because I looked at the README. So others might miss it too.
* Documentation

Update development setup instructions

---

.travis.yml

This PR updates the CI matrix to the latest patch releases.

CI: Use 2.2.10, 2.4.6, 2.5.5, 2.6.2

---

.travis.yml
bin/install_geckodriver.sh

Update a few minor points around travis (Use 16.04, Don't print geckodriver info twice, remove un-required matrix tests)
Speed up travis runs, reduce clutter in logs
The travis runs will show this working (Hopefully)

Travis healthcheck

---

CHANGELOG.md

Fixes typo ('rals' --> 'rails')

---

.rubocop.yml
cucumber-rails.gemspec

Update rubocop and rubocop-rspec.
Keep things up-to-date.

Update RuboCop dependencies

---

Appraisals
CONTRIBUTING.md
README.md
cucumber-rails.gemspec
gemfiles/rails_4_2.gemfile
gemfiles/rails_5_0.gemfile
gemfiles/rails_6_0.gemfile

First of 3 small tickets, update the dependencies, and review which ones are needed
Update runtime / dev dependencies, with detailed reasons why in SHA's.
Need to take a look at these after a long time of being left in the cold
CI

Dependency Review / Update

---

Appraisals
README.md
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_2.gemfile
gemfiles/rails_6_0.gemfile

Minor tweaks to gemfiles
Use only officially cut rails in CI
CI

Rails Version Tidy

---

CHANGELOG.md
cucumber-rails.gemspec
lib/cucumber/rails.rb

Release v2 - And make a slight tweak to not have aruba be a runtime dep
CI

Release v2

---

CHANGELOG.md
features/capybara_javascript_drivers.feature
features/database_cleaner.feature
features/step_definitions/cucumber_rails_steps.rb
lib/cucumber/rails.rb
lib/cucumber/rails/database.rb
lib/cucumber/rails/database/deletion_strategy.rb
lib/cucumber/rails/database/shared_connection_strategy.rb
lib/cucumber/rails/database/strategy.rb
lib/cucumber/rails/database/truncation_strategy.rb
spec/cucumber/rails/database_spec.rb

After some deep digging, we do not test for this anywhere in our codebase
Add some extra tests covering a whole heap of scenarios we never covered before
Refactor the Strategy code to be a little more granular, removing the large mega-class and having some better definitions of our defaults
This helps triage a couple of config issues that were reported and could have been bugs
Huge amount of new stuff has been added
Adding new tests, refactoring code

Javascript tagged scenarios - Better documentation

---

features/capybara_javascript_drivers.feature

Fix third test from same issue as first test
Fix 2nd test having issue with new assertion on UTC timezone
Rename some cukes

Quick fixes for tests missed in first fix.

---

cucumber-rails.gemspec

Reduce the size of the gem by removing unneeded files from the package.
Reduce the gem size from **40K** to **27K**, a saving of **33%**!
<details>
<summary><b>contents diff</b> (click me)</summary>
```diff
- Appraisals
- Gemfile
- Rakefile
- bin/install_geckodriver.sh
- bin/install_webpacker.sh
- config/cucumber.yml
- cucumber-rails.gemspec
- dev_tasks/cucumber.rake
- dev_tasks/rspec.rake
- dev_tasks/yard.rake
- dev_tasks/yard/default/layout/html/bubble_32x32.png
- dev_tasks/yard/default/layout/html/footer.erb
- dev_tasks/yard/default/layout/html/index.erb
- dev_tasks/yard/default/layout/html/layout.erb
- dev_tasks/yard/default/layout/html/logo.erb
- dev_tasks/yard/default/layout/html/setup.rb
- features/allow_rescue.feature
- features/annotations.feature
- …
```

Reduce gem package size

---

README.md

Small change. I forgot to update README as part of #526

Add rails 7 to readme

---

.gitignore
cucumber-rails.gemspec

Update development dependencies and other development-related fixes.
- Update appraisal now that the issue blocking the update is fixed.
- Relax the version range of aruba so the latest version can be used.
- Ignore .ruby-gemset for developers who use gemsets.
Improve development, and keep things up to date.
This only affects development and testing, so I ran the test suite. No failures.

Development updates

---

CHANGELOG.md

Changelog entry for https://github.com/cucumber/cucumber-rails/pull/575

update changelog with support rails 7.1 entry
